site_name: jaxqualin

theme: mkdocs    # This theme is mandatory for now, see below

nav:
  - Home: index.md
  - Examples:
    - Fitting the ringdown: notebooks/fit_testing.ipynb
    - Mode search: notebooks/mode_selection_testing.ipynb
  - Results: paper-results.md

plugins:
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: True

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets

extra_javascript:
  - docs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
